name: Refresh Bling Token

on:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas
  workflow_dispatch:       # Permite execução manual

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Chamada da função de refresh
        run: curl -X GET https://consultaestoque.vercel.app/api/refresh
